// Major Indian cities for IPRS registration flow autocomplete.
export const INDIAN_CITIES = [
  "Agra",
  "Ahmedabad",
  "Ajmer",
  "Akola",
  "Aligarh",
  "Allahabad (Prayagraj)",
  "Ambala",
  "Amravati",
  "Amritsar",
  "Anantapur",
  "Asansol",
  "Aurangabad (Chhatrapati Sambhajinagar)",
  "Bareilly",
  "Belgaum (Belagavi)",
  "Bengaluru",
  "Bhagalpur",
  "Bhavnagar",
  "Bhilai",
  "Bhiwandi",
  "Bhopal",
  "Bhubaneswar",
  "Bikaner",
  "Bilaspur",
  "Bokaro Steel City",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Delhi",
  "Dhanbad",
  "Dhule",
  "Durgapur",
  "Erode",
  "Faridabad",
  "Firozabad",
  "Gandhinagar",
  "Gaya",
  "Ghaziabad",
  "Gorakhpur",
  "Gulbarga (Kalaburagi)",
  "Guntur",
  "Gurugram (Gurgaon)",
  "Guwahati",
  "Gwalior",
  "Haldwani",
  "Haridwar",
  "Howrah",
  "Hubballi-Dharwad",
  "Hyderabad",
  "Imphal",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jalgaon",
  "Jammu",
  "Jamnagar",
  "Jamshedpur",
  "Jhansi",
  "Jodhpur",
  "Kakinada",
  "Kalyan-Dombivli",
  "Kanpur",
  "Karnal",
  "Kochi",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Kota",
  "Kozhikode",
  "Kurnool",
  "Latur",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Maheshtala",
  "Malegaon",
  "Mangaluru (Mangalore)",
  "Mathura",
  "Meerut",
  "Mira-Bhayandar",
  "Moradabad",
  "Mumbai",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysuru (Mysore)",
  "Nadiad",
  "Nagpur",
  "Nanded",
  "Nashik",
  "Navi Mumbai",
  "Nellore",
  "Noida",
  "Panaji",
  "Panihati",
  "Panipat",
  "Patiala",
  "Patna",
  "Pimpri-Chinchwad",
  "Puducherry",
  "Pune",
  "Raipur",
  "Rajahmundry",
  "Rajkot",
  "Ranchi",
  "Rourkela",
  "Sagar",
  "Saharanpur",
  "Salem",
  "Sangli-Miraj & Kupwad",
  "Shillong",
  "Shimla",
  "Shivamogga (Shimoga)",
  "Siliguri",
  "Solapur",
  "Sonipat",
  "Srinagar",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Thrissur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tiruppur",
  "Udaipur",
  "Ujjain",
  "Ulhasnagar",
  "Vadodara",
  "Varanasi",
  "Vasai-Virar",
  "Vellore",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal",
];
