export const ALIASES = {
  "panjabi": "Punjabi",
  "bodo (india)": "Bodo",
  "oriya": "Odia",
};

export const EXTRA_SEARCH_KEYS = {
  "punjabi": "Punjabi",
  "meitei": "Manipuri",
  "panjabi": "Punjabi",
  "oriya": "Odia",
  "hinduri": "Hinduri",
  "hinukh": "Hinukh"
};

export const INDIAN_LANGUAGES = new Set([
  "Assamese", "Bengali", "Bodo", "Dogri", "Gujarati", "Hindi", "Kannada", "Kashmiri",
  "Konkani", "Maithili", "Malayalam", "Manipuri", "Marathi", "Nepali", "Odia", "Punjabi",
  "Sanskrit", "Santali", "Sindhi", "Tamil", "Telugu", "Urdu", "Bhojpuri", "English",
  "Hinduri", "Hinukh", "Haryanvi", "Rajasthani", "Marwari", "Chhattisgarhi", "Magahi",
  "Angika", "Garhwali", "Kumaoni", "Tulu", "Kodava", "Bhili", "Gondi"
]);

export const LOCALIZED_LANGUAGE_NAMES = {
  hi: {
    "Hindi": "हिन्दी",
    "Marathi": "मराठी",
    "Gujarati": "गुजराती",
    "Bengali": "बंगाली",
    "Punjabi": "पंजाबी",
    "Bhojpuri": "भोजपुरी",
    "Assamese": "असमिया",
    "Bodo": "बोडो",
    "Dogri": "डोगरी",
    "Kannada": "कन्नड़",
    "Kashmiri": "कश्मीरी",
    "Konkani": "कोंकणी",
    "Maithili": "मैथिली",
    "Malayalam": "मलयालम",
    "Manipuri": "मणिपुरी",
    "Nepali": "नेपाली",
    "Odia": "ओडिया",
    "Sanskrit": "संस्कृत",
    "Santali": "संथाली",
    "Sindhi": "सिंधी",
    "Tamil": "तमिल",
    "Telugu": "तेलुगु",
    "Urdu": "उर्दू",
    "English": "अंग्रेजी",
    "Hinduri": "हिंदूरी",
    "Hinukh": "हिनुख",
    "Haryanvi": "हरियाणवी",
    "Rajasthani": "राजस्थानी",
    "Marwari": "मारवाड़ी",
    "Chhattisgarhi": "छत्तीसगढ़ी",
    "Magahi": "मगही",
    "Angika": "अंगिका",
    "Garhwali": "गढ़वाली",
    "Kumaoni": "कुमाऊँनी",
    "Tulu": "तुळू",
    "Kodava": "कोडव",
    "Bhili": "भीली",
    "Gondi": "गोंडी",
    "Arabic": "अरबी",
    "Persian": "फ़ारसी",
    "Spanish": "स्पैनिश",
    "French": "फ्रेंच",
    "German": "जर्मन",
    "Russian": "रूसी",
    "Chinese": "चीनी",
    "Japanese": "जापानी",
    "Korean": "कोरियाई"
  },
  mr: {
    "Hindi": "हिंदी",
    "Marathi": "मराठी",
    "Gujarati": "गुजराती",
    "Bengali": "बंगाली",
    "Punjabi": "पंजाबी",
    "Bhojpuri": "भोजपुरी",
    "Assamese": "आसामी",
    "Bodo": "बोडो",
    "Dogri": "डोगरी",
    "Kannada": "कन्नड",
    "Kashmiri": "काश्मिरी",
    "Konkani": "कोंकणी",
    "Maithili": "मैथिली",
    "Malayalam": "मल्याळम",
    "Manipuri": "मणिपुरी",
    "Nepali": "नेपाली",
    "Odia": "ओडिया",
    "Sanskrit": "संस्कृत",
    "Santali": "संथाली",
    "Sindhi": "सिंधी",
    "Tamil": "तमिळ",
    "Telugu": "तेलगू",
    "Urdu": "उर्दू",
    "English": "इंग्रजी",
    "Hinduri": "हिंदूरी",
    "Hinukh": "हिनुख",
    "Haryanvi": "हरियाणवी",
    "Rajasthani": "राजस्थानी",
    "Marwari": "मारवाड़ी",
    "Chhattisgarhi": "छत्तीसगढी",
    "Magahi": "मगही",
    "Angika": "अंगिका",
    "Garhwali": "गढवाली",
    "Kumaoni": "कुमाऊंनी",
    "Tulu": "तुळू",
    "Kodava": "कोडव",
    "Bhili": "भीली",
    "Gondi": "गोंडी"
  },
  gu: {
    "Hindi": "હિન્દી",
    "Marathi": "મરાઠી",
    "Gujarati": "ગુજરાતી",
    "Bengali": "બંગાળી",
    "Punjabi": "પંજાબી",
    "Bhojpuri": "ભોજપુરી",
    "Assamese": "અસમિયા",
    "Bodo": "બોડો",
    "Dogri": "ડોગરી",
    "Kannada": "કન્નડ",
    "Kashmiri": "કાશ્મીરી",
    "Konkani": "કોંકણી",
    "Maithili": "મૈથિલી",
    "Malayalam": "મલયાલમ",
    "Manipuri": "મણિપુરી",
    "Nepali": "નેપાળી",
    "Odia": "ઓડિયા",
    "Sanskrit": "સંસ્કૃત",
    "Santali": "સંથાલી",
    "Sindhi": "સિંધી",
    "Tamil": "તમિલ",
    "Telugu": "તેલુગુ",
    "Urdu": "ઉર્દૂ",
    "English": "અંગ્રેજી",
    "Hinduri": "હિંદૂરી",
    "Hinukh": "હિનુખ",
    "Haryanvi": "હરિયાણવી",
    "Rajasthani": "રાજસ્થાની",
    "Marwari": "મારવાડી",
    "Chhattisgarhi": "છત્તીસગઢી",
    "Magahi": "મગહી",
    "Angika": "અંગિકા",
    "Garhwali": "ગઢવાલી",
    "Kumaoni": "કુમાઉની",
    "Tulu": "તુલુ",
    "Kodava": "કોડવા",
    "Bhili": "ભીલી",
    "Gondi": "ગોંડી"
  },
  bn: {
    "Hindi": "হিন্দি",
    "Marathi": "মারাঠি",
    "Gujarati": "গুজরাটি",
    "Bengali": "বাংলা",
    "Punjabi": "পাঞ্জাবি",
    "Bhojpuri": "ভোজপুরি",
    "Assamese": "অসমীয়া",
    "Bodo": "বোডো",
    "Dogri": "ডোগরি",
    "Kannada": "কন্নড়",
    "Kashmiri": "কাশ্মীরি",
    "Konkani": "কোঙ্কণি",
    "Maithili": "মৈথিলি",
    "Malayalam": "মালয়ালম",
    "Manipuri": "মণিপুরি",
    "Nepali": "নেপালি",
    "Odia": "ওড়িয়া",
    "Sanskrit": "সংস্কৃত",
    "Santali": "সাঁওতালি",
    "Sindhi": "সিন্ধি",
    "Tamil": "তামিল",
    "Telugu": "তেলুগু",
    "Urdu": "উর্দু",
    "English": "ইংরেজি",
    "Hinduri": "হিন্দুরি",
    "Hinukh": "হিনুখ",
    "Haryanvi": "হরিয়ানভি",
    "Rajasthani": "রাজস্থানি",
    "Marwari": "মারওয়াড়ি",
    "Chhattisgarhi": "ছত্তিশগড়ি",
    "Magahi": "মগহি",
    "Angika": " অঙ্গিকা",
    "Garhwali": "গাড়োয়ালি",
    "Kumaoni": "কুমাওনি",
    "Tulu": "তুলু",
    "Kodava": "কোডভা",
    "Bhili": "ভিলি",
    "Gondi": "গোন্ডি"
  }
};

export const NATIVE_LANGUAGE_NAMES = {
  "Hindi": "हिन्दी",
  "Marathi": "मराठी",
  "Gujarati": "ગુજરાતી",
  "Bengali": "বাংলা",
  "Punjabi": "ਪੰਜਾਬੀ",
  "Bhojpuri": "भोजपुरी",
  "Assamese": "অসমীয়া",
  "Bodo": "बर'",
  "Dogri": "डोगरी",
  "Kannada": "ಕನ್ನಡ",
  "Kashmiri": "کٲشُر",
  "Konkani": "कोंकणी",
  "Maithili": "मैथिली",
  "Malayalam": "മലയാളം",
  "Manipuri": "ꯃꯩꯇꯩꯂꯣꯟ",
  "Nepali": "नेपाली",
  "Odia": "ଓଡ଼ିଆ",
  "Sanskrit": "संस्कृतम्",
  "Santali": "ᱥᱟᱱᱛᱟᱲᱤ",
  "Sindhi": "सिंधी",
  "Tamil": "தமிழ்",
  "Telugu": "తెలుగు",
  "Urdu": "اردو",
  "English": "English",
  "Hinduri": "हिंदूरी",
  "Hinukh": "гьиндугъас мацI",
  "Haryanvi": "हरियाणवी",
  "Rajasthani": "राजस्थानी",
  "Marwari": "मारवाड़ी",
  "Chhattisgarhi": "छत्तीसगढ़ी",
  "Magahi": "मगही",
  "Angika": "अंगिका",
  "Garhwali": "गढ़वाली",
  "Kumaoni": "कुमाऊँनी",
  "Tulu": "ತುಳು",
  "Kodava": "ಕೊಡವ",
  "Bhili": "भीली",
  "Gondi": "गोंडी"
};
